kaspar:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  
  
  # Position Controllers ---------------------------------------
  arm_r_0_controller:
    type: effort_controllers/JointPositionController
    joint: arm_r_0_joint
    pid: {p: 0.8, i: 0.6, d: 0.3, i_clamp: 1}
  arm_r_1_controller:
    type: effort_controllers/JointPositionController
    joint: arm_r_1_joint
    pid: {p: 0.8, i: 0.6, d: 0.3, i_clamp: 1}
  arm_r_2_controller:
    type: effort_controllers/JointPositionController
    joint: arm_r_2_joint
    pid: {p: 0.8, i: 0.6, d: 0.3, i_clamp: 1}
  arm_r_3_controller:
    type: effort_controllers/JointPositionController
    joint: arm_r_3_joint
    pid: {p: 0.8, i: 0.6, d: 0.3, i_clamp: 1}
  torso_controller:
    type: effort_controllers/JointPositionController
    joint: torso_joint
    pid: {p: 0.8, i: 0.6, d: 0.3, i_clamp: 1}